# Generated by Django 3.2.18 on 2023-06-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "contract",
                    models.TextField(primary_key=True, serialize=False, unique=True),
                ),
                ("frame", models.IntegerField(default=0)),
                ("slot", models.IntegerField(default=1)),
                ("port", models.IntegerField(default=0)),
                ("onu_id", models.IntegerField(default=0)),
                ("olt", models.IntegerField(default=1)),
                ("fsp", models.TextField(default="0/1/0")),
                ("fspi", models.TextField(default="0/1/0/0")),
                ("name_1", models.TextField()),
                ("name_2", models.TextField()),
                ("status", models.TextField(default="online")),
                ("state", models.TextField(default="active")),
                ("sn", models.TextField(default="48575443--------")),
                ("device", models.TextField(default="EG145V5")),
                ("plan_name", models.TextField(default="OZ_0_1")),
                ("provider", models.TextField(default="INTER")),
                ("plan_idx", models.SmallIntegerField(default=210)),
                ("srv_profile", models.SmallIntegerField(default=210)),
                ("line_profile", models.SmallIntegerField(default=3)),
                ("gem_port", models.SmallIntegerField(default=20)),
                ("spid", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.TextField(unique=True)),
                ("password", models.TextField()),
                ("user_type", models.TextField()),
            ],
        ),
    ]
