# Generated by Django 3.2.18 on 2023-05-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.TextField(unique=True)),
                ("password", models.TextField()),
                ("user_type", models.TextField()),
            ],
        ),
    ]
