# Generated by Django 3.2.18 on 2023-06-14 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plans",
            fields=[
                (
                    "plan_name",
                    models.TextField(primary_key=True, serialize=False, unique=True),
                ),
                ("plan_idx", models.IntegerField()),
                ("srv_profile", models.IntegerField()),
                ("line_profile", models.IntegerField()),
                ("gem_port", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="clients",
            name="gem_port",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="line_profile",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="plan_idx",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="srv_profile",
        ),
        migrations.AlterField(
            model_name="clients",
            name="plan_name",
            field=models.ForeignKey(
                db_column="plan_name",
                on_delete=django.db.models.deletion.CASCADE,
                to="db_api.plans",
            ),
        ),
    ]
