# Generated by Django 3.2.18 on 2023-06-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "contract",
                    models.TextField(primary_key=True, serialize=False, unique=True),
                ),
                ("frame", models.SmallIntegerField()),
                ("slot", models.SmallIntegerField()),
                ("port", models.SmallIntegerField()),
                ("onu_id", models.SmallIntegerField()),
                ("name_1", models.TextField()),
                ("name_2", models.TextField()),
            ],
        ),
    ]
