# Generated by Django 3.2.18 on 2023-06-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_api", "0002_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="device",
            field=models.TextField(default="EG145V5"),
        ),
        migrations.AddField(
            model_name="client",
            name="last_down_cause",
            field=models.TextField(default="dying-gasp"),
        ),
        migrations.AddField(
            model_name="client",
            name="last_down_date",
            field=models.TextField(default="-"),
        ),
        migrations.AddField(
            model_name="client",
            name="last_down_time",
            field=models.TextField(default="-"),
        ),
        migrations.AddField(
            model_name="client",
            name="plan",
            field=models.TextField(default="-"),
        ),
        migrations.AddField(
            model_name="client",
            name="sn",
            field=models.TextField(default="-"),
        ),
        migrations.AddField(
            model_name="client",
            name="state",
            field=models.TextField(default="active"),
        ),
        migrations.AddField(
            model_name="client",
            name="status",
            field=models.TextField(default="online"),
        ),
        migrations.AddField(
            model_name="client",
            name="vlan",
            field=models.TextField(default="-"),
        ),
    ]
