# Generated by Django 3.2.18 on 2023-06-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_api", "0003_auto_20230606_0531"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="fsp",
            field=models.TextField(default="0/1/0"),
        ),
    ]
