# Generated by Django 3.2.18 on 2023-07-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_api", "0004_auto_20230731_1604"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarms",
            name="alarm_id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
