# Generated by Django 3.2.18 on 2023-08-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_api", "0005_alter_alarms_alarm_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ports",
            fields=[
                (
                    "port_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("frame", models.IntegerField(default=0)),
                ("slot", models.IntegerField(default=1)),
                ("port", models.IntegerField(default=0)),
                ("olt", models.IntegerField(default=1)),
                ("fspo", models.TextField(default="0/1/0-1", unique=True)),
                ("is_open", models.BooleanField(default=False)),
            ],
        ),
    ]
