# Generated by Django 4.2.5 on 2023-11-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0007_oltpasswords'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACLRules',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(default='-')),
                ('rtr_acl_name', models.TextField(default='-')),
                ('olt_acl_name', models.TextField(default='-')),
                ('rtr_rule_id', models.IntegerField(default=1)),
                ('olt_rule_id', models.IntegerField(default=1)),
                ('ip_addr', models.TextField(default='-')),
            ],
        ),
    ]
