# Generated by Django 4.2.5 on 2024-01-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0008_aclrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='ports',
            name='oid',
            field=models.TextField(default=''),
        ),
    ]
